export const egyptGovernorates = [
  { label: "Cairo", value: "cairo" },
  { label: "Alexandria", value: "alexandria" },
  { label: "Giza", value: "giza" },
  { label: "Qalyubia", value: "qalyubia" },
  { label: "Dakahlia", value: "dakahlia" },
  { label: "Monufia", value: "monufia" },
  { label: "Sharkia", value: "sharkia" },
  { label: "Gharbia", value: "gharbia" },
  { label: "Kafr El Sheikh", value: "kafr_el_sheikh" },
  { label: "Damietta", value: "damietta" },
  { label: "Port Said", value: "port_said" }, 
  { label: "Ismailia", value: "ismailia" },
  { label: "Suez", value: "suez" },
  { label: "Fayoum", value: "fayoum" },
  { label: "Beni Suef", value: "beni_suef" },
  { label: "Minya", value: "minya" },
  { label: "Assiut", value: "assiut" },
  { label: "Sohag", value: "sohag" },
  { label: "Qena", value: "qena" },
  { label: "Luxor", value: "luxor" },
  { label: "Aswan", value: "aswan" },
  { label: "Red Sea", value: "red_sea" },
  { label: "New Valley", value: "new_valley" },
  { label: "Matrouh", value: "matrouh" },
  { label: "North Sinai", value: "north_sinai" },
  { label: "South Sinai", value: "south_sinai" },
  { label: "Beheira", value: "beheira" },
];