export const govUniversities = [
  { value: "cairo_uni", label: "cairo_uni", city: "giza" },
  { value: "alex_uni", label: "alex_uni", city: "alexandria" },
  { value: "ain_shams_uni", label: "ain_shams_uni", city: "cairo" },
  { value: "mansoura_uni", label: "mansoura_uni", city: "dakahlia" },
  { value: "tanta_uni", label: "tanta_uni", city: "gharbia" },
  { value: "assiut_uni", label: "assiut_uni", city: "assiut" },
  { value: "azhar_uni", label: "azhar_uni", city: "cairo" },
  { value: "minia_uni", label: "minia_uni", city: "minia" },
  { value: "beni_suef_uni", label: "beni_suef_uni", city: "beni_suef" },
  { value: "suez_canal_uni", label: "suez_canal_uni", city: "ismailia" },
  { value: "zagazig_uni", label: "zagazig_uni", city: "sharqia" },
  { value: "helwan_uni", label: "helwan_uni", city: "cairo" },
  {
    value: "kafr_elshiekh_uni",
    label: "kafr_elshiekh_uni",
    city: "kafr_el_sheikh",
  },
  { value: "fayoum_uni", label: "fayoum_uni", city: "fayoum" },
  { value: "sohag_uni", label: "sohag_uni", city: "sohag" },
  { value: "aswan_uni", label: "aswan_uni", city: "aswan" },
  { value: "south_valley_uni", label: "south_valley_uni", city: "qena" },
  { value: "port_said_uni", label: "port_said_uni", city: "port_said" },
  { value: "sadat_uni", label: "sadat_uni", city: "monufia" },
  { value: "domiat_uni", label: "domiat_uni", city: "damietta" },
];
